name: Terraform CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      trigger_repo: bn-ritesh-chavan/cicd-app
